# Generated by Django 2.1.7 on 2019-02-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prac1', '0002_plant_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_image',
            field=models.ImageField(null=True, upload_to='media/plant_pics', verbose_name='img'),
        ),
    ]
